export const mockAssets = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    price: 47250,
    change24h: 1245,
    changePercent24h: 2.7,
    marketCap: '₹936B',
    volume24h: '₹28.4B',
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    price: 2580,
    change24h: 95,
    changePercent24h: 3.8,
    marketCap: '₹310B',
    volume24h: '₹14.2B',
  },
  {
    symbol: 'XRP',
    name: 'Ripple',
    price: 2.15,
    change24h: 0.12,
    changePercent24h: 5.9,
    marketCap: '₹115B',
    volume24h: '₹3.2B',
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    price: 198.5,
    change24h: 4.2,
    changePercent24h: 2.2,
    marketCap: '₹88B',
    volume24h: '₹2.8B',
  },
  {
    symbol: 'ADA',
    name: 'Cardano',
    price: 0.92,
    change24h: 0.08,
    changePercent24h: 9.5,
    marketCap: '₹32B',
    volume24h: '₹1.1B',
  },
  {
    symbol: 'DOGE',
    name: 'Dogecoin',
    price: 0.38,
    change24h: 0.05,
    changePercent24h: 15.2,
    marketCap: '₹56B',
    volume24h: '₹1.9B',
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    price: 38.25,
    change24h: 1.15,
    changePercent24h: 3.1,
    marketCap: '₹15B',
    volume24h: '₹580M',
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    price: 14.75,
    change24h: 0.35,
    changePercent24h: 2.4,
    marketCap: '₹7.4B',
    volume24h: '₹650M',
  },
];

export const mockLeaderboard = [
  { rank: 1, username: 'CryptoKing', profit: '+₹8,245', profitPercent: '+82.45%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cryptoking' },
  { rank: 2, username: 'TradeMaster', profit: '+₹6,128', profitPercent: '+61.28%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=trademaster' },
  { rank: 3, username: 'BlockchainBob', profit: '+₹4,567', profitPercent: '+45.67%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=blockchainedbob' },
  { rank: 4, username: 'ETHEnthusiast', profit: '+₹3,890', profitPercent: '+38.90%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ethenthusiast' },
  { rank: 5, username: 'BitcoinBabe', profit: '+₹3,245', profitPercent: '+32.45%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bitcoinbabe' },
  { rank: 6, username: 'MoonMoon', profit: '+₹2,890', profitPercent: '+28.90%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=moonmoon' },
  { rank: 7, username: 'RektRecovery', profit: '+₹2,145', profitPercent: '+21.45%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rektrecovery' },
  { rank: 8, username: 'Hodler2025', profit: '+₹1,890', profitPercent: '+18.90%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hodler2025' },
  { rank: 9, username: 'SwingTrader', profit: '+₹1,234', profitPercent: '+12.34%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=swingtrader' },
  { rank: 10, username: 'YieldFarmer', profit: '+₹890', profitPercent: '+8.90%', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yieldfarmer' },
];

export const currentUserLeaderboard = { rank: 42, username: 'YourUsername', profit: '+$345', profitPercent: '+3.45%' };
